# Generated by Django 3.0.5 on 2020-05-28 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketinvleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('companyDescription', models.TextField()),
                ('symbol', models.CharField(max_length=5)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('price', models.FloatField(blank=True, max_length=4)),
                ('low_high', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
