# Generated by Django 3.0.5 on 2020-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketinvleague', '0003_auto_20200528_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='marketCap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ytdChange',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
    ]
