# Generated by Django 3.0.5 on 2020-06-09 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketinvleague', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='waitlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None),
        ),
    ]
